# Generated by Django 5.1.4 on 2024-12-24 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, unique=True)),
                ('victory', models.PositiveIntegerField(default=0)),
                ('defeaut', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='RoomConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25, unique=True)),
                ('max_players', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'room_config',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('game_start_time', models.DateTimeField(blank=True, null=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='theme.theme')),
                ('room_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room.roomconfig')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.IntegerField(blank=True, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('final', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_players', to='room.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_players', to='room.room')),
            ],
            options={
                'db_table': 'room_players',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='rooms', through='room.RoomPlayer', to='room.player'),
        ),
        migrations.AddConstraint(
            model_name='roomplayer',
            constraint=models.UniqueConstraint(fields=('room', 'player'), name='unique_room_player'),
        ),
    ]
