# Generated by Django 5.1.4 on 2024-12-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomplayer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
