# Generated by Django 5.1.4 on 2024-12-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_roomplayer_score'),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='theme.theme'),
        ),
    ]
