# Generated by Django 5.1.4 on 2024-12-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=20)),
                ('start', models.TextField(max_length=100)),
                ('final', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'theme',
            },
        ),
    ]
